- name: Audit sécurité utilisateurs (password policy, comptes inactifs, etc.)
  hosts: all
  become: yes
  gather_facts: no

  vars:
    remote_script_path: /ansible-tmp/check_users_security_v3.sh
    local_report_dir: /ansible-tmp

  tasks:

    - name: Créer le répertoire temporaire sur l’hôte
      ansible.builtin.file:
        path: /ansible-tmp
        state: directory
        mode: '0755'

    - name: Copier le script d’audit sur l’hôte
      copy:
        src: ./files/check_users_security_v3.sh
        dest: "{{ remote_script_path }}"
        mode: '0755'

    - name: Vérifier la valeur du chemin
      debug:
        var: remote_script_path

    - name: Exécuter le script sur l’hôte distant
      shell: "{{ remote_script_path }}"
      become: true
      args:
        executable: /bin/bash

    - name: Créer le répertoire local pour les rapports de cet hôte
      ansible.builtin.file:
        path: "./reports/{{ inventory_hostname }}"
        state: directory
      delegate_to: localhost
      become: true
      


    - name: Récupérer le rapport CSV 
      fetch:
        src: /ansible-tmp/user_account_audit.csv
        dest: "{{ local_report_dir }}/{{ inventory_hostname }}/user_account_audit.csv"
        flat: yes
        become: true
    
    - name: Récupérer le rapport HTML
      fetch:
        src: /ansible-tmp/user_account_audit.html
        dest: "{{ local_report_dir }}/{{ inventory_hostname }}/user_account_audit.html"
        flat: yes
        become: true


    
    - name: Nettoyer les fichiers temporaires
      file:
        path: "/ansible-tmp/{{ item }}"
        state: absent
        become: true
      loop:
        - check_users_security_v3.sh
        - user_account_audit.csv
        - user_account_audit.html  